### ISSUE TITLE
Add AppVeyor badge to README

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node-storage#10]
Right?

**Comment by lukesneeringer** [comment]
Any idea what the correct Markdown is?

**Comment by stephenplusplus** [comment]
[![AppVeyor Status](https://ci.appveyor.com/api/projects/status/github/googlecloudplatform/google-cloud-node-storage?svg=true)](https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-node-storage)

```md
[![AppVeyor Status](https://ci.appveyor.com/api/projects/status/github/googlecloudplatform/google-cloud-node-storage?svg=true)](https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-node-storage)
```

**Comment by lukesneeringer** [comment]
Thanks. Adding to repo-tools.

**Comment by lukesneeringer** [comment]
https://github.com/GoogleCloudPlatform/nodejs-repo-tools/pull/29

Closing this prematurely.
