### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node-storage#7]
Such as: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by lukesneeringer** [comment]
@jdobry has added this to nodejs-repo-tools ([here](https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/2.0.0/templates/nodejs/issue_template.tpl))
